version: '3.1'

services:

  mongo:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 17017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Produtos_Api_B'
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
